In [10]:
import numpy as np
matrix = [[1,2],[3,4]]

In [12]:
matrix = np.array(matrix)
-matrix 
print(-matrix)
print(np.arange(2)[:,np.newaxis])
matrix += np.arange(2)
matrix

[[-1 -3]
 [-3 -5]]
[[0]
 [1]]


array([[1, 4],
       [3, 6]])